FROM scratch

ADD influxdb /usr/bin/influxdb
ADD config.sample.toml /etc/influxdb/config.toml

EXPOSE 8083 8086 8090 8099

VOLUME /etc/influxdb/

ENTRYPOINT ["/usr/bin/influxdb", "-config=/etc/influxdb/config.toml"]
