#!/bin/ash

CONFIG_FILE="/etc/influxdb/config.toml"

#Configure InfluxDB Cluster
if [ -n "${HOSTNAME}" ]; then
	if [ "${HOSTNAME}" == "auto" ]; then
		#set hostname with IPv4 eth0
		HOSTIPNAME=$(ip a show dev eth0 | grep inet | grep eth0 | sed -e 's/^.*inet.//g' -e 's/\/.*$//g')
		sed -i "s/^# hostname.*$/hostname = \"${HOSTIPNAME}\"/g" ${CONFIG_FILE}
	else
		sed -i "s/^# hostname.*$/hostname = \"${HOSTNAME}\"/g" ${CONFIG_FILE}
	fi
fi

if [ -n "${SEED}" ]; then
  sed -i "s/^# seed-servers.*$/seed-servers = [\"${SEED}\"]/g" ${CONFIG_FILE}
fi

if [ -n "${REPLICATION_FACTOR}" ]; then
	sed -i "s/replication-factor = 1/replication-factor = ${REPLICATION_FACTOR}/g" ${CONFIG_FILE}
fi

echo "=> Starting InfluxDB ..."

exec /usr/bin/influxdb -config=/etc/influxdb/config.toml
